package puregojaccl

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/ml-explore/mlx-c/internal/mlxcgen/apilock"
)

// Options controls generated JACCL purego bindings.
type Options struct {
	PackageName string
	TargetName  string
	ToolName    string
}

// Generate returns formatted Go files for the JACCL purego package.
func Generate(lock *apilock.Lock, opts Options) (map[string][]byte, error) {
	if lock == nil {
		return nil, fmt.Errorf("generate purego jaccl: nil api lock")
	}
	if opts.PackageName == "" {
		opts.PackageName = "jacclc"
	}
	if opts.TargetName == "" {
		opts.TargetName = "jacclc"
	}
	if opts.ToolName == "" {
		opts.ToolName = "mlx-c-gen-purego-jaccl"
	}
	target, ok := lock.Targets[opts.TargetName]
	if !ok {
		return nil, fmt.Errorf("generate purego jaccl: target %q not found", opts.TargetName)
	}
	if err := validateTarget(target); err != nil {
		return nil, err
	}

	files := map[string]string{
		"doc.gen.go":       genDoc(opts),
		"lib.gen.go":       genLib(opts),
		"types.gen.go":     genTypes(opts, target),
		"functions.gen.go": genFunctions(opts, target),
	}
	out := make(map[string][]byte, len(files))
	for name, src := range files {
		formatted, err := format.Source([]byte(src))
		if err != nil {
			return nil, fmt.Errorf("format %s: %w", name, err)
		}
		out[name] = formatted
	}
	return out, nil
}

func validateTarget(target apilock.Target) error {
	structs := map[string]bool{}
	for _, st := range target.Structs {
		if !st.Opaque {
			return fmt.Errorf("generate purego jaccl: struct %s is not opaque", st.Name)
		}
		structs[st.Name] = true
	}
	for _, name := range []string{"mlx_jaccl_group", "mlx_jaccl_config"} {
		if !structs[name] {
			return fmt.Errorf("generate purego jaccl: missing struct %s", name)
		}
	}
	enums := map[string]bool{}
	for _, enum := range target.Enums {
		enums[enum.Name] = true
	}
	if !enums["mlx_jaccl_dtype"] {
		return fmt.Errorf("generate purego jaccl: missing enum mlx_jaccl_dtype")
	}
	for _, fn := range target.Functions {
		if !strings.HasPrefix(fn.Name, "mlx_jaccl_") {
			return fmt.Errorf("generate purego jaccl: unexpected function %s", fn.Name)
		}
	}
	return nil
}

func header(opts Options) string {
	return fmt.Sprintf("// Code generated by %s from codegen/mlxc-capi.lock.json; DO NOT EDIT.\n\n", opts.ToolName)
}

func genDoc(opts Options) string {
	return header(opts) + fmt.Sprintf(`// Package %s provides purego bindings for libjacclc.
package %s
`, opts.PackageName, opts.PackageName)
}

func genLib(opts Options) string {
	return header(opts) + fmt.Sprintf(`package %s

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sync"
	"sync/atomic"

	"github.com/ebitengine/purego"
)

const (
	envLibraryPath    = "MLX_C_JACCLC_LIB_PATH"
	envLibraryPathAlt = "MLX_JACCLC_LIB_PATH"
)

var (
	loadMu            sync.Mutex
	jacclcLib         uintptr
	jacclcLoaded      atomic.Uintptr
	loadedLibraryPath string
)

// LibraryPath returns the loaded libjacclc path.
func LibraryPath() string {
	loadMu.Lock()
	defer loadMu.Unlock()
	return loadedLibraryPath
}

// Load loads libjacclc from the environment or standard library locations.
func Load() error {
	return loadPath("")
}

// LoadPath loads libjacclc from path. If path is a directory, it is expected
// to contain libjacclc and its sibling dependencies.
func LoadPath(path string) error {
	return loadPath(path)
}

func ensureLoaded() error {
	if jacclcLoaded.Load() != 0 {
		return nil
	}
	return Load()
}

func loadPath(path string) error {
	loadMu.Lock()
	defer loadMu.Unlock()
	if jacclcLib != 0 {
		if path == "" || sameLibraryPath(path, loadedLibraryPath) {
			return nil
		}
		return fmt.Errorf("jacclc already loaded from %%s", loadedLibraryPath)
	}
	if path == "" {
		resolved, err := resolveLibraryPath()
		if err != nil {
			return err
		}
		path = resolved
	} else {
		path = resolveLibraryOverride(path)
	}
	if err := preloadSiblingLibraries(path); err != nil {
		return err
	}
	lib, err := purego.Dlopen(path, purego.RTLD_NOW|purego.RTLD_GLOBAL)
	if err != nil {
		return fmt.Errorf("load %%s: %%w", path, err)
	}
	if err := registerJACCLFunctions(lib); err != nil {
		return err
	}
	jacclcLib = lib
	loadedLibraryPath = path
	jacclcLoaded.Store(lib)
	return nil
}

func sameLibraryPath(path, loaded string) bool {
	path = resolveLibraryOverride(path)
	if path == loaded {
		return true
	}
	absPath, err1 := filepath.Abs(path)
	absLoaded, err2 := filepath.Abs(loaded)
	return err1 == nil && err2 == nil && absPath == absLoaded
}

func resolveLibraryPath() (string, error) {
	for _, name := range []string{envLibraryPath, envLibraryPathAlt} {
		if value := os.Getenv(name); value != "" {
			return resolveLibraryOverride(value), nil
		}
	}

	libName := libraryFileName("libjacclc")
	for _, dir := range sourceSearchDirs() {
		candidate := filepath.Join(dir, libName)
		if _, err := os.Stat(candidate); err == nil {
			return candidate, nil
		}
	}

	paths := []string{
		filepath.Join(os.Getenv("HOME"), "lib", libName),
		filepath.Join(os.Getenv("HOME"), ".local", "lib", libName),
		"/usr/local/lib/" + libName,
	}
	if runtime.GOOS == "darwin" {
		paths = append(paths, "/opt/homebrew/lib/"+libName)
	}
	for _, path := range paths {
		if _, err := os.Stat(path); err == nil {
			return path, nil
		}
	}
	return "", fmt.Errorf("libjacclc not found; set %%s to a libjacclc file or directory", envLibraryPath)
}

func sourceSearchDirs() []string {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return nil
	}
	dir := filepath.Dir(file)
	for depth := 0; depth < 10; depth++ {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return []string{
				filepath.Join(dir, "build-shared"),
				filepath.Join(dir, "build-Release"),
				filepath.Join(dir, "build-Debug"),
				filepath.Join(dir, "build"),
				filepath.Join(dir, "install", "lib"),
			}
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return nil
		}
		dir = parent
	}
	return nil
}

func resolveLibraryOverride(path string) string {
	info, err := os.Stat(path)
	if err != nil || !info.IsDir() {
		return path
	}
	return filepath.Join(path, libraryFileName("libjacclc"))
}

func libraryFileName(base string) string {
	switch runtime.GOOS {
	case "darwin":
		return base + ".dylib"
	case "linux":
		return base + ".so"
	default:
		return base
	}
}

func preloadSiblingLibraries(path string) error {
	dir := filepath.Dir(path)
	for _, base := range []string{"libjaccl", "libmlx"} {
		candidate := filepath.Join(dir, libraryFileName(base))
		if _, err := os.Stat(candidate); err != nil {
			continue
		}
		if _, err := purego.Dlopen(candidate, purego.RTLD_NOW|purego.RTLD_GLOBAL); err != nil {
			return fmt.Errorf("preload %%s: %%w", candidate, err)
		}
	}
	return nil
}

func registerLibFunc(fptr any, lib uintptr, name string) (err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("register %%s: %%v", name, r)
		}
	}()
	purego.RegisterLibFunc(fptr, lib, name)
	return nil
}
`, opts.PackageName)
}

func genTypes(opts Options, target apilock.Target) string {
	var b bytes.Buffer
	fmt.Fprint(&b, header(opts))
	fmt.Fprintf(&b, "package %s\n\n", opts.PackageName)
	fmt.Fprintln(&b, "import \"unsafe\"")
	fmt.Fprintln(&b)

	structs := append([]apilock.Struct(nil), target.Structs...)
	sort.Slice(structs, func(i, j int) bool { return structs[i].Name < structs[j].Name })
	for _, st := range structs {
		name := goStructName(st.Name)
		fmt.Fprintf(&b, "// %s wraps %s.\n", name, st.Name)
		fmt.Fprintf(&b, "type %s struct {\n\tctx unsafe.Pointer\n}\n\n", name)
		fmt.Fprintf(&b, "// Ptr returns the underlying pointer.\n")
		fmt.Fprintf(&b, "func (t %s) Ptr() unsafe.Pointer {\n\treturn t.ctx\n}\n\n", name)
		fmt.Fprintf(&b, "// IsNil reports whether the underlying pointer is nil.\n")
		fmt.Fprintf(&b, "func (t %s) IsNil() bool {\n\treturn t.ctx == nil\n}\n\n", name)
		fmt.Fprintf(&b, "func (t %s) handle() unsafe.Pointer {\n\treturn t.ctx\n}\n\n", name)
		fmt.Fprintf(&b, "func %sFromHandle(handle unsafe.Pointer) %s {\n\treturn %s{ctx: handle}\n}\n\n",
			lowerFirst(name), name, name)
	}

	for _, enum := range target.Enums {
		if enum.Name != "mlx_jaccl_dtype" {
			continue
		}
		fmt.Fprintln(&b, "// DType is a JACCL element type.")
		fmt.Fprintln(&b, "type DType int32")
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, "const (")
		for _, value := range enum.Values {
			fmt.Fprintf(&b, "\t%s DType = %d\n", goEnumValueName(value.Name), value.Value)
		}
		fmt.Fprintln(&b, ")")
		fmt.Fprintln(&b)
	}
	return b.String()
}

func genFunctions(opts Options, target apilock.Target) string {
	var b bytes.Buffer
	fmt.Fprint(&b, header(opts))
	fmt.Fprintf(&b, "package %s\n\n", opts.PackageName)
	fmt.Fprintln(&b, "import (")
	fmt.Fprintln(&b, "\t\"errors\"")
	fmt.Fprintln(&b, "\t\"fmt\"")
	fmt.Fprintln(&b, "\t\"runtime\"")
	fmt.Fprintln(&b, "\t\"unsafe\"")
	fmt.Fprintln(&b, ")")
	fmt.Fprintln(&b)

	functions := append([]apilock.Function(nil), target.Functions...)
	sort.Slice(functions, func(i, j int) bool { return functions[i].Name < functions[j].Name })
	for _, fn := range functions {
		fmt.Fprintf(&b, "var _%s %s\n", fn.Name, rawFuncType(fn))
	}
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "func registerJACCLFunctions(lib uintptr) error {")
	fmt.Fprintln(&b, "\tvar errs []error")
	for _, fn := range functions {
		fmt.Fprintf(&b, "\tif err := registerLibFunc(&_%s, lib, %q); err != nil {\n", fn.Name, fn.Name)
		fmt.Fprintln(&b, "\t\terrs = append(errs, err)")
		fmt.Fprintln(&b, "\t}")
	}
	fmt.Fprintln(&b, "\treturn errors.Join(errs...)")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)

	fmt.Fprintln(&b, "func cString(s string) []byte {")
	fmt.Fprintln(&b, "\tb := make([]byte, len(s)+1)")
	fmt.Fprintln(&b, "\tcopy(b, s)")
	fmt.Fprintln(&b, "\treturn b")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "func goString(p *byte) string {")
	fmt.Fprintln(&b, "\tif p == nil {")
	fmt.Fprintln(&b, "\t\treturn \"\"")
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintln(&b, "\tn := 0")
	fmt.Fprintln(&b, "\tfor *(*byte)(unsafe.Add(unsafe.Pointer(p), n)) != 0 {")
	fmt.Fprintln(&b, "\t\tn++")
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintln(&b, "\treturn string(unsafe.Slice(p, n))")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// CError reports an error returned by libjacclc.")
	fmt.Fprintln(&b, "type CError struct {")
	fmt.Fprintln(&b, "\tCall string")
	fmt.Fprintln(&b, "\tMsg  string")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "func (e CError) Error() string {")
	fmt.Fprintln(&b, "\tif e.Msg == \"\" {")
	fmt.Fprintf(&b, "\t\treturn fmt.Sprintf(\"%%s failed\", e.Call)\n")
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintf(&b, "\treturn fmt.Sprintf(\"%%s: %%s\", e.Call, e.Msg)\n")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "func lastCError(name string) error {")
	fmt.Fprintln(&b, "\tmsg := goString(_mlx_jaccl_last_error())")
	fmt.Fprintln(&b, "\treturn CError{Call: name, Msg: msg}")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "func lastCErrorIfAny(name string) error {")
	fmt.Fprintln(&b, "\tmsg := goString(_mlx_jaccl_last_error())")
	fmt.Fprintln(&b, "\tif msg == \"\" {")
	fmt.Fprintln(&b, "\t\treturn nil")
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintln(&b, "\treturn CError{Call: name, Msg: msg}")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "func statusError(name string, status int32) error {")
	fmt.Fprintln(&b, "\tif status == 0 {")
	fmt.Fprintln(&b, "\t\treturn nil")
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintln(&b, "\treturn lastCError(name)")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)

	for _, fn := range functions {
		writeWrapper(&b, fn)
	}
	writeConvenience(&b)
	return b.String()
}

func writeConvenience(b *bytes.Buffer) {
	fmt.Fprintln(b, "// NewConfig creates a JACCL configuration.")
	fmt.Fprintln(b, "func NewConfig() (Config, error) {")
	fmt.Fprintln(b, "\treturn ConfigNew()")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "// NewConfigFromEnv creates a JACCL configuration from environment variables.")
	fmt.Fprintln(b, "func NewConfigFromEnv() (Config, error) {")
	fmt.Fprintln(b, "\treturn ConfigFromEnv()")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "// NewGroup creates an empty JACCL group.")
	fmt.Fprintln(b, "func NewGroup() (Group, error) {")
	fmt.Fprintln(b, "\treturn GroupNew()")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "// NewGroupFromEnv initializes a JACCL group from environment variables.")
	fmt.Fprintln(b, "func NewGroupFromEnv(strict bool) (Group, error) {")
	fmt.Fprintln(b, "\treturn Init(strict)")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "// NewGroupWithConfig initializes a JACCL group from config.")
	fmt.Fprintln(b, "func NewGroupWithConfig(config Config, strict bool) (Group, error) {")
	fmt.Fprintln(b, "\treturn InitConfig(config, strict)")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "// Close releases config.")
	fmt.Fprintln(b, "func (config Config) Close() error {")
	fmt.Fprintln(b, "\treturn ConfigFree(config)")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "// SetRank sets config's rank.")
	fmt.Fprintln(b, "func (config Config) SetRank(rank int) error {")
	fmt.Fprintln(b, "\treturn ConfigSetRank(config, rank)")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "// Rank returns config's rank.")
	fmt.Fprintln(b, "func (config Config) Rank() (int, error) {")
	fmt.Fprintln(b, "\treturn ConfigRank(config)")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "// SetCoordinator sets config's coordinator address.")
	fmt.Fprintln(b, "func (config Config) SetCoordinator(coordinator string) error {")
	fmt.Fprintln(b, "\treturn ConfigSetCoordinator(config, coordinator)")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "// Coordinator returns config's coordinator address.")
	fmt.Fprintln(b, "func (config Config) Coordinator() (string, error) {")
	fmt.Fprintln(b, "\treturn ConfigCoordinator(config)")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "// PreferRing sets whether config prefers ring topology.")
	fmt.Fprintln(b, "func (config Config) PreferRing(prefer bool) error {")
	fmt.Fprintln(b, "\treturn ConfigPreferRing(config, prefer)")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "// PrefersRing reports whether config prefers ring topology.")
	fmt.Fprintln(b, "func (config Config) PrefersRing() (bool, error) {")
	fmt.Fprintln(b, "\treturn ConfigPrefersRing(config)")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "// Size returns config's size.")
	fmt.Fprintln(b, "func (config Config) Size() (int, error) {")
	fmt.Fprintln(b, "\treturn ConfigSize(config)")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "// IsValidMesh reports whether config describes a valid mesh.")
	fmt.Fprintln(b, "func (config Config) IsValidMesh() (bool, error) {")
	fmt.Fprintln(b, "\treturn ConfigIsValidMesh(config)")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "// IsValidRing reports whether config describes a valid ring.")
	fmt.Fprintln(b, "func (config Config) IsValidRing() (bool, error) {")
	fmt.Fprintln(b, "\treturn ConfigIsValidRing(config)")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "// SetDevicesFile sets devices from a JSON file.")
	fmt.Fprintln(b, "func (config Config) SetDevicesFile(path string) error {")
	fmt.Fprintln(b, "\treturn ConfigSetDevicesFile(config, path)")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "// SetDevicesJSON sets devices from a JSON string.")
	fmt.Fprintln(b, "func (config Config) SetDevicesJSON(data string) error {")
	fmt.Fprintln(b, "\treturn ConfigSetDevicesJSON(config, data)")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "// Close releases group.")
	fmt.Fprintln(b, "func (group Group) Close() error {")
	fmt.Fprintln(b, "\treturn GroupFree(group)")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "// Rank returns group's rank.")
	fmt.Fprintln(b, "func (group Group) Rank() (int, error) {")
	fmt.Fprintln(b, "\treturn GroupRank(group)")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "// Size returns group's size.")
	fmt.Fprintln(b, "func (group Group) Size() (int, error) {")
	fmt.Fprintln(b, "\treturn GroupSize(group)")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
}

func rawFuncType(fn apilock.Function) string {
	params := make([]string, 0, len(fn.Parameters))
	for _, param := range fn.Parameters {
		typ, _ := splitParam(param)
		params = append(params, rawGoType(typ))
	}
	ret := rawGoType(fn.Return)
	if ret == "" {
		return fmt.Sprintf("func(%s)", strings.Join(params, ", "))
	}
	return fmt.Sprintf("func(%s) %s", strings.Join(params, ", "), ret)
}

func writeWrapper(b *bytes.Buffer, fn apilock.Function) {
	name := goFuncName(fn.Name)
	cgoName := fn.Name
	if isInitFunction(fn) {
		writeInitWrapper(b, fn, name)
		return
	}
	params := wrapperParams(fn)
	callArgs, setup, keepAlive := wrapperCallArgs(fn.Parameters)
	result := wrapperResult(fn)

	fmt.Fprintf(b, "// %s calls %s.\n", name, cgoName)
	fmt.Fprintf(b, "func %s(%s) %s {\n", name, strings.Join(params, ", "), result)
	fmt.Fprint(b, "\tif err := ensureLoaded(); err != nil {\n")
	writeLoadReturn(b, fn)
	fmt.Fprint(b, "\t}\n")
	for _, line := range setup {
		fmt.Fprintf(b, "\t%s\n", line)
	}
	fmt.Fprintln(b, "\truntime.LockOSThread()")
	fmt.Fprintln(b, "\tdefer runtime.UnlockOSThread()")
	writeCallAndReturn(b, fn, callArgs, keepAlive)
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
}

func writeInitWrapper(b *bytes.Buffer, fn apilock.Function, name string) {
	params := []string{}
	for _, param := range fn.Parameters[1:] {
		typ, pname := splitParam(param)
		params = append(params, fmt.Sprintf("%s %s", safeParamName(pname), publicGoType(typ)))
	}
	callArgs, setup, keepAlive := wrapperCallArgs(fn.Parameters[1:])
	callArgs = append([]string{"&res"}, callArgs...)
	fmt.Fprintf(b, "// %s calls %s.\n", name, fn.Name)
	fmt.Fprintf(b, "func %s(%s) (Group, error) {\n", name, strings.Join(params, ", "))
	fmt.Fprintln(b, "\tif err := ensureLoaded(); err != nil {")
	fmt.Fprintln(b, "\t\treturn Group{}, err")
	fmt.Fprintln(b, "\t}")
	fmt.Fprintln(b, "\tvar res Group")
	for _, line := range setup {
		fmt.Fprintf(b, "\t%s\n", line)
	}
	fmt.Fprintln(b, "\truntime.LockOSThread()")
	fmt.Fprintln(b, "\tdefer runtime.UnlockOSThread()")
	fmt.Fprintf(b, "\tstatus := _%s(%s)\n", fn.Name, strings.Join(callArgs, ", "))
	for _, line := range keepAlive {
		fmt.Fprintf(b, "\t%s\n", line)
	}
	fmt.Fprintf(b, "\tif err := statusError(%q, status); err != nil {\n", fn.Name)
	fmt.Fprintln(b, "\t\treturn Group{}, err")
	fmt.Fprintln(b, "\t}")
	fmt.Fprintln(b, "\treturn res, nil")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
}

func wrapperParams(fn apilock.Function) []string {
	params := make([]string, 0, len(fn.Parameters))
	for _, param := range fn.Parameters {
		typ, name := splitParam(param)
		params = append(params, fmt.Sprintf("%s %s", safeParamName(name), publicGoType(typ)))
	}
	return params
}

func wrapperResult(fn apilock.Function) string {
	switch fn.Return {
	case "void", "int":
		if fn.Return == "int" && isValueIntFunction(fn.Name) {
			return "(int, error)"
		}
		return "error"
	case "bool":
		return "(bool, error)"
	case "size_t":
		return "(uint, error)"
	case "const char*":
		return "(string, error)"
	case "mlx_jaccl_group":
		return "(Group, error)"
	case "mlx_jaccl_config":
		return "(Config, error)"
	default:
		return "(" + rawGoType(fn.Return) + ", error)"
	}
}

func writeLoadReturn(b *bytes.Buffer, fn apilock.Function) {
	ret := fn.Return
	switch ret {
	case "void", "int":
		if ret == "int" && isValueIntFunction(fn.Name) {
			fmt.Fprintln(b, "\t\treturn 0, err")
			return
		}
		fmt.Fprintln(b, "\t\treturn err")
	case "bool":
		fmt.Fprintln(b, "\t\treturn false, err")
	case "size_t":
		fmt.Fprintln(b, "\t\treturn 0, err")
	case "const char*":
		fmt.Fprintln(b, "\t\treturn \"\", err")
	case "mlx_jaccl_group":
		fmt.Fprintln(b, "\t\treturn Group{}, err")
	case "mlx_jaccl_config":
		fmt.Fprintln(b, "\t\treturn Config{}, err")
	default:
		fmt.Fprintf(b, "\t\tvar zero %s\n", rawGoType(ret))
		fmt.Fprintln(b, "\t\treturn zero, err")
	}
}

func writeCallAndReturn(b *bytes.Buffer, fn apilock.Function, callArgs, keepAlive []string) {
	call := fmt.Sprintf("_%s(%s)", fn.Name, strings.Join(callArgs, ", "))
	switch fn.Return {
	case "void":
		fmt.Fprintf(b, "\t%s\n", call)
		writeKeepAlive(b, keepAlive)
		fmt.Fprintln(b, "\treturn nil")
	case "int":
		if isValueIntFunction(fn.Name) {
			fmt.Fprintf(b, "\tvalue := int(%s)\n", call)
			writeKeepAlive(b, keepAlive)
			fmt.Fprintln(b, "\tif value < 0 {")
			fmt.Fprintf(b, "\t\treturn value, lastCError(%q)\n", fn.Name)
			fmt.Fprintln(b, "\t}")
			fmt.Fprintln(b, "\treturn value, nil")
			return
		}
		fmt.Fprintf(b, "\tstatus := %s\n", call)
		writeKeepAlive(b, keepAlive)
		fmt.Fprintf(b, "\treturn statusError(%q, status)\n", fn.Name)
	case "bool":
		fmt.Fprintf(b, "\tvalue := %s\n", call)
		writeKeepAlive(b, keepAlive)
		fmt.Fprintln(b, "\tif !value {")
		fmt.Fprintf(b, "\t\tif err := lastCErrorIfAny(%q); err != nil {\n", fn.Name)
		fmt.Fprintln(b, "\t\t\treturn false, err")
		fmt.Fprintln(b, "\t\t}")
		fmt.Fprintln(b, "\t}")
		fmt.Fprintln(b, "\treturn value, nil")
	case "size_t":
		fmt.Fprintf(b, "\tvalue := %s\n", call)
		writeKeepAlive(b, keepAlive)
		fmt.Fprintln(b, "\tif value == 0 {")
		fmt.Fprintf(b, "\t\tif err := lastCErrorIfAny(%q); err != nil {\n", fn.Name)
		fmt.Fprintln(b, "\t\t\treturn 0, err")
		fmt.Fprintln(b, "\t\t}")
		fmt.Fprintln(b, "\t}")
		fmt.Fprintln(b, "\treturn value, nil")
	case "const char*":
		fmt.Fprintf(b, "\tptr := %s\n", call)
		writeKeepAlive(b, keepAlive)
		fmt.Fprintln(b, "\tif ptr == nil {")
		fmt.Fprintf(b, "\t\tif err := lastCErrorIfAny(%q); err != nil {\n", fn.Name)
		fmt.Fprintln(b, "\t\t\treturn \"\", err")
		fmt.Fprintln(b, "\t\t}")
		fmt.Fprintln(b, "\t\treturn \"\", nil")
		fmt.Fprintln(b, "\t}")
		fmt.Fprintln(b, "\treturn goString(ptr), nil")
	case "mlx_jaccl_group":
		fmt.Fprintf(b, "\thandle := %s\n", call)
		writeKeepAlive(b, keepAlive)
		fmt.Fprintln(b, "\treturn groupFromHandle(handle), nil")
	case "mlx_jaccl_config":
		fmt.Fprintf(b, "\thandle := %s\n", call)
		writeKeepAlive(b, keepAlive)
		fmt.Fprintf(b, "\tvalue := configFromHandle(handle)\n")
		fmt.Fprintln(b, "\tif value.IsNil() {")
		fmt.Fprintf(b, "\t\tif err := lastCErrorIfAny(%q); err != nil {\n", fn.Name)
		fmt.Fprintln(b, "\t\t\treturn Config{}, err")
		fmt.Fprintln(b, "\t\t}")
		fmt.Fprintln(b, "\t}")
		fmt.Fprintln(b, "\treturn value, nil")
	default:
		fmt.Fprintf(b, "\tvalue := %s\n", call)
		writeKeepAlive(b, keepAlive)
		fmt.Fprintln(b, "\treturn value, nil")
	}
}

func writeKeepAlive(b *bytes.Buffer, lines []string) {
	for _, line := range lines {
		fmt.Fprintf(b, "\t%s\n", line)
	}
}

func wrapperCallArgs(params []string) ([]string, []string, []string) {
	var args, setup, keepAlive []string
	for _, param := range params {
		typ, name := splitParam(param)
		name = safeParamName(name)
		switch typ {
		case "mlx_jaccl_group", "mlx_jaccl_config":
			args = append(args, name+".handle()")
		case "int":
			args = append(args, "int32("+name+")")
		case "const char*":
			local := name + "Bytes"
			setup = append(setup, fmt.Sprintf("%s := cString(%s)", local, name))
			args = append(args, "&"+local+"[0]")
			keepAlive = append(keepAlive, "runtime.KeepAlive("+local+")")
		default:
			args = append(args, name)
		}
	}
	return args, setup, keepAlive
}

func rawGoType(typ string) string {
	switch typ {
	case "void":
		return ""
	case "int":
		return "int32"
	case "bool":
		return "bool"
	case "size_t":
		return "uint"
	case "const char*":
		return "*byte"
	case "const void*", "void*":
		return "unsafe.Pointer"
	case "mlx_jaccl_dtype":
		return "DType"
	case "mlx_jaccl_group", "mlx_jaccl_config":
		return "unsafe.Pointer"
	case "mlx_jaccl_group*":
		return "*Group"
	default:
		return typ
	}
}

func publicGoType(typ string) string {
	switch typ {
	case "int":
		return "int"
	case "const char*":
		return "string"
	case "const void*", "void*":
		return "unsafe.Pointer"
	case "mlx_jaccl_group":
		return "Group"
	case "mlx_jaccl_config":
		return "Config"
	default:
		return rawGoType(typ)
	}
}

func splitParam(param string) (typ, name string) {
	param = strings.TrimSpace(param)
	idx := strings.LastIndexByte(param, ' ')
	if idx < 0 {
		return param, ""
	}
	return strings.TrimSpace(param[:idx]), strings.TrimSpace(param[idx+1:])
}

func goStructName(name string) string {
	name = strings.TrimPrefix(name, "mlx_jaccl_")
	return camel(name)
}

func goEnumValueName(name string) string {
	name = strings.TrimPrefix(name, "MLX_JACCL_")
	return "DType" + camel(strings.ToLower(name))
}

func goFuncName(name string) string {
	name = strings.TrimPrefix(name, "mlx_jaccl_")
	return camel(name)
}

func camel(name string) string {
	var out strings.Builder
	for _, part := range strings.Split(name, "_") {
		switch strings.ToLower(part) {
		case "":
			continue
		case "bfloat16":
			out.WriteString("BFloat16")
		case "dtype":
			out.WriteString("DType")
		case "json":
			out.WriteString("JSON")
		default:
			out.WriteString(strings.ToUpper(part[:1]))
			out.WriteString(strings.ToLower(part[1:]))
		}
	}
	return out.String()
}

func lowerFirst(name string) string {
	if name == "" {
		return ""
	}
	return strings.ToLower(name[:1]) + name[1:]
}

func safeParamName(name string) string {
	switch name {
	case "json":
		return "data"
	case "n_bytes":
		return "nBytes"
	}
	return name
}

func isInitFunction(fn apilock.Function) bool {
	return fn.Return == "int" && (fn.Name == "mlx_jaccl_init" || fn.Name == "mlx_jaccl_init_config")
}

func isValueIntFunction(name string) bool {
	switch name {
	case "mlx_jaccl_config_rank",
		"mlx_jaccl_config_size",
		"mlx_jaccl_group_rank",
		"mlx_jaccl_group_size":
		return true
	}
	return false
}
