package plan

import (
	"strings"
	"testing"

	"github.com/ml-explore/mlx-c/internal/mlxcgen/inventory"
)

func TestGeneratedOutputsIncludeRecentHeaderMappings(t *testing.T) {
	got := map[string]bool{}
	for _, out := range GeneratedOutputs() {
		got[out] = true
	}
	for _, want := range []string{
		"mlx/c/cuda.h",
		"mlx/c/cuda.cpp",
		"mlx/c/graph_utils.h",
		"mlx/c/graph_utils.cpp",
		"mlx/c/private/vector.h",
	} {
		if !got[want] {
			t.Fatalf("GeneratedOutputs missing %s", want)
		}
	}
}

func TestCheckInventory(t *testing.T) {
	var entries []inventory.Entry
	for _, out := range GeneratedOutputs() {
		entries = append(entries, inventory.Entry{
			Kind:   "generated_header_api",
			Target: "mlxc",
			Path:   out,
		})
	}
	if err := CheckInventory(entries); err != nil {
		t.Fatal(err)
	}
}

func TestCheckInventoryRejectsDrift(t *testing.T) {
	err := CheckInventory([]inventory.Entry{{
		Kind:   "generated_header_api",
		Target: "mlxc",
		Path:   "mlx/c/not_planned.h",
	}})
	if err == nil || !strings.Contains(err.Error(), "not generated by the Go plan") {
		t.Fatalf("CheckInventory error = %v", err)
	}
}
