package plan

import (
	"reflect"
	"strings"
	"testing"

	"github.com/ml-explore/mlx-c/internal/mlxcgen/inventory"
)

func TestDefaultManifestPreservesPlan(t *testing.T) {
	headers, err := HeaderMappings()
	if err != nil {
		t.Fatal(err)
	}
	wantHeaders := []HeaderMapping{
		{Name: "ops", Headers: []string{"mlx/ops.h", "mlx/einsum.h"}, Docstring: "Core array operations"},
		{Name: "linalg", Headers: []string{"mlx/linalg.h"}, Docstring: "Linear algebra operations"},
		{Name: "random", Headers: []string{"mlx/random.h"}, Docstring: "Random number operations"},
		{Name: "fft", Headers: []string{"mlx/fft.h"}, Docstring: "FFT operations"},
		{Name: "fast", Headers: []string{"mlx/fast.h"}, Docstring: "Fast custom operations"},
		{Name: "io", Headers: []string{"mlx/io.h"}, Docstring: "IO operations"},
		{Name: "compile", Headers: []string{"mlx/compile.h", "mlx/compile_impl.h"}, Docstring: "Compilation operations"},
		{Name: "transforms", Headers: []string{"mlx/transforms.h"}, Docstring: "Transform operations"},
		{
			Name:        "transforms_impl",
			Headers:     []string{"mlx/transforms_impl.h"},
			Docstring:   "Implementation detail operations",
			PreIncludes: []string{"mlx/array.h", "mlx/transforms.h"},
		},
		{Name: "memory", Headers: []string{"mlx/memory.h"}, Docstring: "Memory operations"},
		{Name: "metal", Headers: []string{"mlx/backend/metal/metal.h"}, Docstring: "Metal specific operations"},
		{Name: "cuda", Headers: []string{"mlx/backend/cuda/cuda.h"}, Docstring: "Cuda specific operations"},
		{Name: "graph_utils", Headers: []string{"mlx/graph_utils.h"}, Docstring: "Graph Utils"},
		{Name: "distributed", Headers: []string{"mlx/distributed/ops.h"}, Docstring: "Distributed collectives"},
	}
	if !reflect.DeepEqual(headers, wantHeaders) {
		t.Fatalf("HeaderMappings = %#v, want %#v", headers, wantHeaders)
	}

	standalone, err := StandaloneNames()
	if err != nil {
		t.Fatal(err)
	}
	wantStandalone := []string{"vector", "closure", "map"}
	if !reflect.DeepEqual(standalone, wantStandalone) {
		t.Fatalf("StandaloneNames = %#v, want %#v", standalone, wantStandalone)
	}

	variants, err := VariantMappings()
	if err != nil {
		t.Fatal(err)
	}
	arange := variants["mlx_core"]["arange"]
	if len(arange) != 9 {
		t.Fatalf("arange variants length = %d, want 9", len(arange))
	}
	if arange[0].Signature != "array(double, double, double, Dtype, StreamOrDevice)" {
		t.Fatalf("arange first signature = %q", arange[0].Signature)
	}
	if arange[0].Suffix == nil || *arange[0].Suffix != "" {
		t.Fatalf("arange first variant = %#v, want base suffix", arange[0])
	}
	if !arange[1].Skip {
		t.Fatalf("arange second variant = %#v, want skip", arange[1])
	}
	if got := variants["mlx_core_fft"]["fftn"]; len(got) != 3 || !got[1].Skip || !got[2].Skip {
		t.Fatalf("fftn variants = %#v, want base then two skips", got)
	}

	allowedDetail, err := AllowedDetailFunctions()
	if err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"compile", "compile_clear_cache", "compile_erase", "vmap_replace", "vmap_trace"} {
		if !allowedDetail[name] {
			t.Fatalf("AllowedDetailFunctions missing %s", name)
		}
	}
}

func TestGeneratedOutputsIncludeRecentHeaderMappings(t *testing.T) {
	outputs, err := GeneratedOutputs()
	if err != nil {
		t.Fatal(err)
	}
	got := map[string]bool{}
	for _, out := range outputs {
		got[out] = true
	}
	for _, want := range []string{
		"mlx/c/cuda.h",
		"mlx/c/cuda.cpp",
		"mlx/c/graph_utils.h",
		"mlx/c/graph_utils.cpp",
		"mlx/c/private/vector.h",
	} {
		if !got[want] {
			t.Fatalf("GeneratedOutputs missing %s", want)
		}
	}
}

func TestCheckInventory(t *testing.T) {
	outputs, err := GeneratedOutputs()
	if err != nil {
		t.Fatal(err)
	}
	var entries []inventory.Entry
	for _, out := range outputs {
		entries = append(entries, inventory.Entry{
			Kind:   "generated_header_api",
			Target: "mlxc",
			Path:   out,
		})
	}
	if err := CheckInventory(entries); err != nil {
		t.Fatal(err)
	}
}

func TestCheckInventoryRejectsDrift(t *testing.T) {
	err := CheckInventory([]inventory.Entry{{
		Kind:   "generated_header_api",
		Target: "mlxc",
		Path:   "mlx/c/not_planned.h",
	}})
	if err == nil || !strings.Contains(err.Error(), "not generated by the Go plan") {
		t.Fatalf("CheckInventory error = %v", err)
	}
}

func TestLoadManifest(t *testing.T) {
	const manifest = `
headers:
  - name: ops
    headers:
      - mlx/ops.h
    doc: Core array operations
    pre_includes:
      - mlx/array.h
standalone:
  - vector
variant_mappings:
  mlx_core:
    squeeze:
      - signature: "array(array, std::vector<int>, StreamOrDevice)"
        suffix: axes
      - signature: "array(array, int, StreamOrDevice)"
        suffix: axis
      - signature: "array(array, StreamOrDevice)"
        suffix: ""
    grad:
      - signature: "std::function<array(const array&)>(std::function<array(const array&)>)"
        skip: true
allowed_detail_functions:
  - compile
`
	m, err := Load(strings.NewReader(manifest))
	if err != nil {
		t.Fatal(err)
	}
	if len(m.Headers) != 1 || m.Headers[0].Name != "ops" {
		t.Fatalf("headers = %#v", m.Headers)
	}
	if got, want := m.Headers[0].PreIncludes[0], "mlx/array.h"; got != want {
		t.Fatalf("pre include = %q, want %q", got, want)
	}
	outputs := m.GeneratedOutputs()
	for _, want := range []string{"mlx/c/ops.h", "mlx/c/ops.cpp", "mlx/c/private/vector.h"} {
		if !contains(outputs, want) {
			t.Fatalf("GeneratedOutputs missing %s in %v", want, outputs)
		}
	}
	squeeze := m.VariantMappings["mlx_core"]["squeeze"]
	if got, want := squeeze[0].Signature, "array(array, std::vector<int>, StreamOrDevice)"; got != want {
		t.Fatalf("squeeze first signature = %q, want %q", got, want)
	}
	if got, want := *squeeze[0].Suffix, "axes"; got != want {
		t.Fatalf("squeeze first variant = %q, want %q", got, want)
	}
	if got, want := *squeeze[2].Suffix, ""; got != want {
		t.Fatalf("squeeze third variant = %q, want %q", got, want)
	}
	if grad := m.VariantMappings["mlx_core"]["grad"]; len(grad) != 1 || !grad[0].Skip {
		t.Fatalf("grad variants = %#v, want one skip", grad)
	}
	if !m.AllowedDetailFunctionsSet()["compile"] {
		t.Fatalf("AllowedDetailFunctionsSet missing compile")
	}
}

func TestLoadManifestRejectsVariantWithoutDisposition(t *testing.T) {
	const manifest = `
headers:
  - name: ops
    headers:
      - mlx/ops.h
standalone:
  - vector
variant_mappings:
  mlx_core:
    squeeze:
      - signature: "array(array, StreamOrDevice)"
`
	_, err := Load(strings.NewReader(manifest))
	if err == nil || !strings.Contains(err.Error(), "must set exactly one of suffix or skip") {
		t.Fatalf("Load error = %v", err)
	}
}

func TestLoadManifestRejectsDuplicateVariantSignatures(t *testing.T) {
	const manifest = `
headers:
  - name: ops
    headers:
      - mlx/ops.h
standalone:
  - vector
variant_mappings:
  mlx_core:
    squeeze:
      - signature: "array(array, StreamOrDevice)"
        suffix: ""
      - signature: "array(array, StreamOrDevice)"
        skip: true
`
	_, err := Load(strings.NewReader(manifest))
	if err == nil || !strings.Contains(err.Error(), `duplicate signature "array(array, StreamOrDevice)"`) {
		t.Fatalf("Load error = %v", err)
	}
}

func TestLoadManifestRejectsUnknownFields(t *testing.T) {
	const manifest = `
headers:
  - name: ops
    headers:
      - mlx/ops.h
    unknown: value
standalone:
  - vector
`
	_, err := Load(strings.NewReader(manifest))
	if err == nil || !strings.Contains(err.Error(), "field unknown not found") {
		t.Fatalf("Load error = %v", err)
	}
}

func TestLoadManifestRejectsDuplicateHeaderMappings(t *testing.T) {
	const manifest = `
headers:
  - name: ops
    headers:
      - mlx/ops.h
  - name: ops
    headers:
      - mlx/einsum.h
standalone:
  - vector
`
	_, err := Load(strings.NewReader(manifest))
	if err == nil || !strings.Contains(err.Error(), `duplicate header mapping "ops"`) {
		t.Fatalf("Load error = %v", err)
	}
}

func TestLoadManifestRejectsDuplicateAllowedDetailFunctions(t *testing.T) {
	const manifest = `
headers:
  - name: ops
    headers:
      - mlx/ops.h
standalone:
  - vector
allowed_detail_functions:
  - compile
  - compile
`
	_, err := Load(strings.NewReader(manifest))
	if err == nil || !strings.Contains(err.Error(), `duplicate allowed detail function "compile"`) {
		t.Fatalf("Load error = %v", err)
	}
}

func contains(list []string, s string) bool {
	for _, elem := range list {
		if elem == s {
			return true
		}
	}
	return false
}
