package plan

import (
	"fmt"
	"sort"
	"strings"

	"github.com/ml-explore/mlx-c/internal/mlxcgen/inventory"
)

// HeaderMapping defines a header-derived binding output.
type HeaderMapping struct {
	Name        string
	Headers     []string
	Docstring   string
	PreIncludes []string
}

var headerMappings = []HeaderMapping{
	{"ops", []string{"mlx/ops.h", "mlx/einsum.h"}, "Core array operations", nil},
	{"linalg", []string{"mlx/linalg.h"}, "Linear algebra operations", nil},
	{"random", []string{"mlx/random.h"}, "Random number operations", nil},
	{"fft", []string{"mlx/fft.h"}, "FFT operations", nil},
	{"fast", []string{"mlx/fast.h"}, "Fast custom operations", nil},
	{"io", []string{"mlx/io.h"}, "IO operations", nil},
	{"compile", []string{"mlx/compile.h", "mlx/compile_impl.h"}, "Compilation operations", nil},
	{"transforms", []string{"mlx/transforms.h"}, "Transform operations", nil},
	{"transforms_impl", []string{"mlx/transforms_impl.h"}, "Implementation detail operations",
		[]string{"mlx/array.h", "mlx/transforms.h"}},
	{"memory", []string{"mlx/memory.h"}, "Memory operations", nil},
	{"metal", []string{"mlx/backend/metal/metal.h"}, "Metal specific operations", nil},
	{"cuda", []string{"mlx/backend/cuda/cuda.h"}, "Cuda specific operations", nil},
	{"graph_utils", []string{"mlx/graph_utils.h"}, "Graph Utils", nil},
	{"distributed", []string{"mlx/distributed/ops.h"}, "Distributed collectives", nil},
}

var standaloneNames = []string{"vector", "closure", "map"}

// HeaderMappings returns the current header-derived binding plan.
func HeaderMappings() []HeaderMapping {
	return append([]HeaderMapping(nil), headerMappings...)
}

// StandaloneNames returns the current standalone binding plan.
func StandaloneNames() []string {
	return append([]string(nil), standaloneNames...)
}

// GeneratedOutputs returns all files currently produced by the Go generator.
func GeneratedOutputs() []string {
	var out []string
	for _, hm := range headerMappings {
		out = append(out,
			"mlx/c/"+hm.Name+".h",
			"mlx/c/"+hm.Name+".cpp",
		)
	}
	for _, name := range standaloneNames {
		out = append(out,
			"mlx/c/"+name+".h",
			"mlx/c/"+name+".cpp",
			"mlx/c/private/"+name+".h",
		)
	}
	sort.Strings(out)
	return out
}

// CheckInventory verifies that generated inventory entries match the plan.
func CheckInventory(entries []inventory.Entry) error {
	planned := map[string]bool{}
	for _, out := range GeneratedOutputs() {
		planned[out] = true
	}
	entriesByPath := map[string]inventory.Entry{}
	for _, entry := range entries {
		entriesByPath[entry.Path] = entry
	}

	var problems []string
	for path := range planned {
		entry, ok := entriesByPath[path]
		if !ok {
			problems = append(problems, fmt.Sprintf("%s is generated by plan but missing from inventory", path))
			continue
		}
		if entry.Kind != "generated_header_api" && entry.Kind != "generated_support" {
			problems = append(problems, fmt.Sprintf("%s inventory kind = %s, want generated_header_api or generated_support", path, entry.Kind))
		}
	}
	for _, entry := range entries {
		if entry.Kind != "generated_header_api" && entry.Kind != "generated_support" {
			continue
		}
		if !planned[entry.Path] {
			problems = append(problems, fmt.Sprintf("%s is %s but is not generated by the Go plan", entry.Path, entry.Kind))
		}
	}
	if len(problems) > 0 {
		sort.Strings(problems)
		return fmt.Errorf("plan check failed:\n%s", strings.Join(problems, "\n"))
	}
	return nil
}
