// Package customspec loads repo-owned custom C API generation specs.
//
// Custom specs describe C API surfaces that are intentionally not mirrored
// from upstream C++ headers. They are policy inputs for reports and checks;
// they do not make handwritten runtime code generated by themselves.
package customspec
