// Code generated by mlx-c-gen-purego-jaccl from codegen/mlxc-capi.lock.json; DO NOT EDIT.

package jacclc

import (
	"errors"
	"fmt"
	"runtime"
	"unsafe"

	"github.com/ebitengine/purego"
)

//go:linkname puregoSyscall15X github.com/ebitengine/purego.syscall_syscall15X
func puregoSyscall15X(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15 uintptr) (r1, r2, err uintptr)

//go:linkname puregoSyscall15XPtr github.com/ebitengine/purego.syscall_syscall15X
func puregoSyscall15XPtr(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15 uintptr) (r1 unsafe.Pointer, r2, err uintptr)

//go:linkname puregoSyscall15XPtr1 github.com/ebitengine/purego.syscall_syscall15X
func puregoSyscall15XPtr1(fn uintptr, a1 unsafe.Pointer, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15 uintptr) (r1 unsafe.Pointer, r2, err uintptr)

var _mlx_jaccl_all_gather func(unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, uint) int32
var _mlx_jaccl_all_gather_addr uintptr
var _mlx_jaccl_all_max func(unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, uint, DType) int32
var _mlx_jaccl_all_max_addr uintptr
var _mlx_jaccl_all_min func(unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, uint, DType) int32
var _mlx_jaccl_all_min_addr uintptr
var _mlx_jaccl_all_sum func(unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, uint, DType) int32
var _mlx_jaccl_all_sum_addr uintptr
var _mlx_jaccl_barrier func(unsafe.Pointer) int32
var _mlx_jaccl_barrier_addr uintptr
var _mlx_jaccl_clear_error func()
var _mlx_jaccl_clear_error_addr uintptr
var _mlx_jaccl_config_coordinator func(unsafe.Pointer) *byte
var _mlx_jaccl_config_coordinator_addr uintptr
var _mlx_jaccl_config_free func(unsafe.Pointer) int32
var _mlx_jaccl_config_free_addr uintptr
var _mlx_jaccl_config_from_env func() unsafe.Pointer
var _mlx_jaccl_config_from_env_addr uintptr
var _mlx_jaccl_config_is_valid_mesh func(unsafe.Pointer) bool
var _mlx_jaccl_config_is_valid_mesh_addr uintptr
var _mlx_jaccl_config_is_valid_ring func(unsafe.Pointer) bool
var _mlx_jaccl_config_is_valid_ring_addr uintptr
var _mlx_jaccl_config_new func() unsafe.Pointer
var _mlx_jaccl_config_new_out func(*Config) int32
var _mlx_jaccl_config_new_out_addr uintptr
var _mlx_jaccl_config_prefer_ring func(unsafe.Pointer, bool) int32
var _mlx_jaccl_config_prefer_ring_addr uintptr
var _mlx_jaccl_config_prefers_ring func(unsafe.Pointer) bool
var _mlx_jaccl_config_prefers_ring_addr uintptr
var _mlx_jaccl_config_rank func(unsafe.Pointer) int32
var _mlx_jaccl_config_rank_addr uintptr
var _mlx_jaccl_config_set_coordinator func(unsafe.Pointer, *byte) int32
var _mlx_jaccl_config_set_coordinator_addr uintptr
var _mlx_jaccl_config_set_devices_file func(unsafe.Pointer, *byte) int32
var _mlx_jaccl_config_set_devices_file_addr uintptr
var _mlx_jaccl_config_set_devices_json func(unsafe.Pointer, *byte) int32
var _mlx_jaccl_config_set_devices_json_addr uintptr
var _mlx_jaccl_config_set_rank func(unsafe.Pointer, int32) int32
var _mlx_jaccl_config_set_rank_addr uintptr
var _mlx_jaccl_config_size func(unsafe.Pointer) int32
var _mlx_jaccl_config_size_addr uintptr
var _mlx_jaccl_dtype_size func(DType) uint
var _mlx_jaccl_dtype_size_addr uintptr
var _mlx_jaccl_group_free func(unsafe.Pointer) int32
var _mlx_jaccl_group_free_addr uintptr
var _mlx_jaccl_group_new func() unsafe.Pointer
var _mlx_jaccl_group_new_addr uintptr
var _mlx_jaccl_group_rank func(unsafe.Pointer) int32
var _mlx_jaccl_group_rank_addr uintptr
var _mlx_jaccl_group_size func(unsafe.Pointer) int32
var _mlx_jaccl_group_size_addr uintptr
var _mlx_jaccl_init func(*Group, bool) int32
var _mlx_jaccl_init_config func(*Group, unsafe.Pointer, bool) int32
var _mlx_jaccl_is_available func() bool
var _mlx_jaccl_is_available_addr uintptr
var _mlx_jaccl_last_error func() *byte
var _mlx_jaccl_last_error_addr uintptr
var _mlx_jaccl_recv func(unsafe.Pointer, unsafe.Pointer, uint, int32) int32
var _mlx_jaccl_send func(unsafe.Pointer, unsafe.Pointer, uint, int32) int32

func registerJACCLFunctions(lib uintptr) error {
	var errs []error
	if err := registerLibFunc(&_mlx_jaccl_all_gather, lib, "mlx_jaccl_all_gather"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_all_gather"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_all_gather addr: %w", err))
	} else {
		_mlx_jaccl_all_gather_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_all_max, lib, "mlx_jaccl_all_max"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_all_max"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_all_max addr: %w", err))
	} else {
		_mlx_jaccl_all_max_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_all_min, lib, "mlx_jaccl_all_min"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_all_min"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_all_min addr: %w", err))
	} else {
		_mlx_jaccl_all_min_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_all_sum, lib, "mlx_jaccl_all_sum"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_all_sum"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_all_sum addr: %w", err))
	} else {
		_mlx_jaccl_all_sum_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_barrier, lib, "mlx_jaccl_barrier"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_barrier"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_barrier addr: %w", err))
	} else {
		_mlx_jaccl_barrier_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_clear_error, lib, "mlx_jaccl_clear_error"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_clear_error"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_clear_error addr: %w", err))
	} else {
		_mlx_jaccl_clear_error_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_config_coordinator, lib, "mlx_jaccl_config_coordinator"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_config_coordinator"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_config_coordinator addr: %w", err))
	} else {
		_mlx_jaccl_config_coordinator_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_config_free, lib, "mlx_jaccl_config_free"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_config_free"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_config_free addr: %w", err))
	} else {
		_mlx_jaccl_config_free_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_config_from_env, lib, "mlx_jaccl_config_from_env"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_config_from_env"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_config_from_env addr: %w", err))
	} else {
		_mlx_jaccl_config_from_env_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_config_is_valid_mesh, lib, "mlx_jaccl_config_is_valid_mesh"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_config_is_valid_mesh"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_config_is_valid_mesh addr: %w", err))
	} else {
		_mlx_jaccl_config_is_valid_mesh_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_config_is_valid_ring, lib, "mlx_jaccl_config_is_valid_ring"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_config_is_valid_ring"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_config_is_valid_ring addr: %w", err))
	} else {
		_mlx_jaccl_config_is_valid_ring_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_config_new, lib, "mlx_jaccl_config_new"); err != nil {
		errs = append(errs, err)
	}
	if err := registerLibFunc(&_mlx_jaccl_config_new_out, lib, "mlx_jaccl_config_new_out"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_config_new_out"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_config_new_out addr: %w", err))
	} else {
		_mlx_jaccl_config_new_out_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_config_prefer_ring, lib, "mlx_jaccl_config_prefer_ring"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_config_prefer_ring"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_config_prefer_ring addr: %w", err))
	} else {
		_mlx_jaccl_config_prefer_ring_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_config_prefers_ring, lib, "mlx_jaccl_config_prefers_ring"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_config_prefers_ring"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_config_prefers_ring addr: %w", err))
	} else {
		_mlx_jaccl_config_prefers_ring_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_config_rank, lib, "mlx_jaccl_config_rank"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_config_rank"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_config_rank addr: %w", err))
	} else {
		_mlx_jaccl_config_rank_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_config_set_coordinator, lib, "mlx_jaccl_config_set_coordinator"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_config_set_coordinator"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_config_set_coordinator addr: %w", err))
	} else {
		_mlx_jaccl_config_set_coordinator_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_config_set_devices_file, lib, "mlx_jaccl_config_set_devices_file"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_config_set_devices_file"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_config_set_devices_file addr: %w", err))
	} else {
		_mlx_jaccl_config_set_devices_file_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_config_set_devices_json, lib, "mlx_jaccl_config_set_devices_json"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_config_set_devices_json"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_config_set_devices_json addr: %w", err))
	} else {
		_mlx_jaccl_config_set_devices_json_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_config_set_rank, lib, "mlx_jaccl_config_set_rank"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_config_set_rank"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_config_set_rank addr: %w", err))
	} else {
		_mlx_jaccl_config_set_rank_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_config_size, lib, "mlx_jaccl_config_size"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_config_size"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_config_size addr: %w", err))
	} else {
		_mlx_jaccl_config_size_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_dtype_size, lib, "mlx_jaccl_dtype_size"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_dtype_size"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_dtype_size addr: %w", err))
	} else {
		_mlx_jaccl_dtype_size_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_group_free, lib, "mlx_jaccl_group_free"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_group_free"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_group_free addr: %w", err))
	} else {
		_mlx_jaccl_group_free_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_group_new, lib, "mlx_jaccl_group_new"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_group_new"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_group_new addr: %w", err))
	} else {
		_mlx_jaccl_group_new_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_group_rank, lib, "mlx_jaccl_group_rank"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_group_rank"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_group_rank addr: %w", err))
	} else {
		_mlx_jaccl_group_rank_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_group_size, lib, "mlx_jaccl_group_size"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_group_size"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_group_size addr: %w", err))
	} else {
		_mlx_jaccl_group_size_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_init, lib, "mlx_jaccl_init"); err != nil {
		errs = append(errs, err)
	}
	if err := registerLibFunc(&_mlx_jaccl_init_config, lib, "mlx_jaccl_init_config"); err != nil {
		errs = append(errs, err)
	}
	if err := registerLibFunc(&_mlx_jaccl_is_available, lib, "mlx_jaccl_is_available"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_is_available"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_is_available addr: %w", err))
	} else {
		_mlx_jaccl_is_available_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_last_error, lib, "mlx_jaccl_last_error"); err != nil {
		errs = append(errs, err)
	} else if sym, err := purego.Dlsym(lib, "mlx_jaccl_last_error"); err != nil {
		errs = append(errs, fmt.Errorf("register mlx_jaccl_last_error addr: %w", err))
	} else {
		_mlx_jaccl_last_error_addr = sym
	}
	if err := registerLibFunc(&_mlx_jaccl_recv, lib, "mlx_jaccl_recv"); err != nil {
		errs = append(errs, err)
	}
	if err := registerLibFunc(&_mlx_jaccl_send, lib, "mlx_jaccl_send"); err != nil {
		errs = append(errs, err)
	}
	return errors.Join(errs...)
}

const cStringStackMax = 256

func cStringPtr(s string, stack *[cStringStackMax]byte) (*byte, []byte) {
	if len(s) < len(stack) {
		copy(stack[:], s)
		stack[len(s)] = 0
		return &stack[0], nil
	}
	b := make([]byte, len(s)+1)
	copy(b, s)
	return &b[0], b
}

func goString(p *byte) string {
	if p == nil {
		return ""
	}
	n := 0
	for *(*byte)(unsafe.Add(unsafe.Pointer(p), n)) != 0 {
		n++
	}
	return string(unsafe.Slice(p, n))
}

func bytesPointer(b []byte) unsafe.Pointer {
	if len(b) == 0 {
		return nil
	}
	return unsafe.Pointer(&b[0])
}

func allGatherBytesLen(size, elemLen int) (int, error) {
	if size < 0 {
		return 0, fmt.Errorf("all gather: group size %d is negative", size)
	}
	if elemLen < 0 {
		return 0, fmt.Errorf("all gather: input length %d is negative", elemLen)
	}
	max := int(^uint(0) >> 1)
	if elemLen != 0 && size > max/elemLen {
		return 0, fmt.Errorf("all gather: output length overflows int for group size %d and input length %d", size, elemLen)
	}
	return size * elemLen, nil
}

// CError reports an error returned by libjacclc.
type CError struct {
	Call string
	Msg  string
}

func (e CError) Error() string {
	if e.Msg == "" {
		return fmt.Sprintf("%s failed", e.Call)
	}
	return fmt.Sprintf("%s: %s", e.Call, e.Msg)
}

func lastCError(name string) error {
	msg := lastErrorString()
	return CError{Call: name, Msg: msg}
}

func lastCErrorIfAny(name string) error {
	msg := lastErrorString()
	if msg == "" {
		return nil
	}
	return CError{Call: name, Msg: msg}
}

func lastErrorString() string {
	if _mlx_jaccl_last_error_addr != 0 {
		ptr, _, _ := puregoSyscall15XPtr(_mlx_jaccl_last_error_addr, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
		return goString((*byte)(ptr))
	}
	return goString(_mlx_jaccl_last_error())
}

func statusError(name string, status int32) error {
	if status == 0 {
		return nil
	}
	return lastCError(name)
}

func boolUintptr(v bool) uintptr {
	if v {
		return 1
	}
	return 0
}

// AllGather calls mlx_jaccl_all_gather.
func AllGather(group Group, input unsafe.Pointer, output unsafe.Pointer, nBytes uint) error {
	if err := ensureLoaded(); err != nil {
		return err
	}
	r1, _, _ := puregoSyscall15X(_mlx_jaccl_all_gather_addr, uintptr(group.handle()), uintptr(input), uintptr(output), uintptr(nBytes), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	status := int32(r1)
	if status != 0 {
		return lastCError("mlx_jaccl_all_gather")
	}
	return nil
}

// AllMax calls mlx_jaccl_all_max.
func AllMax(group Group, input unsafe.Pointer, output unsafe.Pointer, nBytes uint, dtype DType) error {
	if err := ensureLoaded(); err != nil {
		return err
	}
	r1, _, _ := puregoSyscall15X(_mlx_jaccl_all_max_addr, uintptr(group.handle()), uintptr(input), uintptr(output), uintptr(nBytes), uintptr(dtype), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	status := int32(r1)
	if status != 0 {
		return lastCError("mlx_jaccl_all_max")
	}
	return nil
}

// AllMin calls mlx_jaccl_all_min.
func AllMin(group Group, input unsafe.Pointer, output unsafe.Pointer, nBytes uint, dtype DType) error {
	if err := ensureLoaded(); err != nil {
		return err
	}
	r1, _, _ := puregoSyscall15X(_mlx_jaccl_all_min_addr, uintptr(group.handle()), uintptr(input), uintptr(output), uintptr(nBytes), uintptr(dtype), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	status := int32(r1)
	if status != 0 {
		return lastCError("mlx_jaccl_all_min")
	}
	return nil
}

// AllSum calls mlx_jaccl_all_sum.
func AllSum(group Group, input unsafe.Pointer, output unsafe.Pointer, nBytes uint, dtype DType) error {
	if err := ensureLoaded(); err != nil {
		return err
	}
	r1, _, _ := puregoSyscall15X(_mlx_jaccl_all_sum_addr, uintptr(group.handle()), uintptr(input), uintptr(output), uintptr(nBytes), uintptr(dtype), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	status := int32(r1)
	if status != 0 {
		return lastCError("mlx_jaccl_all_sum")
	}
	return nil
}

// Barrier calls mlx_jaccl_barrier.
func Barrier(group Group) error {
	if err := ensureLoaded(); err != nil {
		return err
	}
	r1, _, _ := puregoSyscall15X(_mlx_jaccl_barrier_addr, uintptr(group.handle()), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	status := int32(r1)
	if status != 0 {
		return lastCError("mlx_jaccl_barrier")
	}
	return nil
}

// ClearError calls mlx_jaccl_clear_error.
func ClearError() error {
	if err := ensureLoaded(); err != nil {
		return err
	}
	_, _, _ = puregoSyscall15X(_mlx_jaccl_clear_error_addr, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	return nil
}

// ConfigCoordinator calls mlx_jaccl_config_coordinator.
func ConfigCoordinator(config Config) (string, error) {
	if err := ensureLoaded(); err != nil {
		return "", err
	}
	ptr, _, _ := puregoSyscall15XPtr1(_mlx_jaccl_config_coordinator_addr, config.handle(), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	if ptr == nil {
		if err := lastCErrorIfAny("mlx_jaccl_config_coordinator"); err != nil {
			return "", err
		}
		return "", nil
	}
	return goString((*byte)(ptr)), nil
}

// ConfigFree calls mlx_jaccl_config_free.
func ConfigFree(config Config) error {
	if err := ensureLoaded(); err != nil {
		return err
	}
	if config.IsNil() {
		r1, _, _ := puregoSyscall15X(_mlx_jaccl_config_free_addr, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
		status := int32(r1)
		if status != 0 {
			return lastCError("mlx_jaccl_config_free")
		}
		return nil
	}
	r1, _, _ := puregoSyscall15X(_mlx_jaccl_config_free_addr, uintptr(config.handle()), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	status := int32(r1)
	if status != 0 {
		return lastCError("mlx_jaccl_config_free")
	}
	return nil
}

// ConfigFromEnv calls mlx_jaccl_config_from_env.
func ConfigFromEnv() (Config, error) {
	if err := ensureLoaded(); err != nil {
		return Config{}, err
	}
	ptr, _, _ := puregoSyscall15XPtr(_mlx_jaccl_config_from_env_addr, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	value := configFromHandle(ptr)
	if value.IsNil() {
		if err := lastCErrorIfAny("mlx_jaccl_config_from_env"); err != nil {
			return Config{}, err
		}
	}
	return value, nil
}

// ConfigIsValidMesh calls mlx_jaccl_config_is_valid_mesh.
func ConfigIsValidMesh(config Config) (bool, error) {
	if err := ensureLoaded(); err != nil {
		return false, err
	}
	if config.IsNil() {
		runtime.LockOSThread()
		defer runtime.UnlockOSThread()
		value := _mlx_jaccl_config_is_valid_mesh(config.handle())
		if !value {
			if err := lastCErrorIfAny("mlx_jaccl_config_is_valid_mesh"); err != nil {
				return false, err
			}
		}
		return value, nil
	}
	r1, _, _ := puregoSyscall15X(_mlx_jaccl_config_is_valid_mesh_addr, uintptr(config.handle()), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	return r1 != 0, nil
}

// ConfigIsValidRing calls mlx_jaccl_config_is_valid_ring.
func ConfigIsValidRing(config Config) (bool, error) {
	if err := ensureLoaded(); err != nil {
		return false, err
	}
	if config.IsNil() {
		runtime.LockOSThread()
		defer runtime.UnlockOSThread()
		value := _mlx_jaccl_config_is_valid_ring(config.handle())
		if !value {
			if err := lastCErrorIfAny("mlx_jaccl_config_is_valid_ring"); err != nil {
				return false, err
			}
		}
		return value, nil
	}
	r1, _, _ := puregoSyscall15X(_mlx_jaccl_config_is_valid_ring_addr, uintptr(config.handle()), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	return r1 != 0, nil
}

// ConfigNew calls mlx_jaccl_config_new.
func ConfigNew() (Config, error) {
	if err := ensureLoaded(); err != nil {
		return Config{}, err
	}
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	handle := _mlx_jaccl_config_new()
	value := configFromHandle(handle)
	if value.IsNil() {
		if err := lastCErrorIfAny("mlx_jaccl_config_new"); err != nil {
			return Config{}, err
		}
	}
	return value, nil
}

// ConfigNewOut calls mlx_jaccl_config_new_out.
func ConfigNewOut() (Config, error) {
	if err := ensureLoaded(); err != nil {
		return Config{}, err
	}
	var res Config
	r1, _, _ := puregoSyscall15X(_mlx_jaccl_config_new_out_addr, uintptr(unsafe.Pointer(&res)), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	status := int32(r1)
	if status != 0 {
		return Config{}, lastCError("mlx_jaccl_config_new_out")
	}
	return res, nil
}

// ConfigPreferRing calls mlx_jaccl_config_prefer_ring.
func ConfigPreferRing(config Config, prefer bool) error {
	if err := ensureLoaded(); err != nil {
		return err
	}
	if config.IsNil() {
		runtime.LockOSThread()
		defer runtime.UnlockOSThread()
		status := _mlx_jaccl_config_prefer_ring(config.handle(), prefer)
		return statusError("mlx_jaccl_config_prefer_ring", status)
	}
	r1, _, _ := puregoSyscall15X(_mlx_jaccl_config_prefer_ring_addr, uintptr(config.handle()), boolUintptr(prefer), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	status := int32(r1)
	if status != 0 {
		return lastCError("mlx_jaccl_config_prefer_ring")
	}
	return nil
}

// ConfigPrefersRing calls mlx_jaccl_config_prefers_ring.
func ConfigPrefersRing(config Config) (bool, error) {
	if err := ensureLoaded(); err != nil {
		return false, err
	}
	if config.IsNil() {
		runtime.LockOSThread()
		defer runtime.UnlockOSThread()
		value := _mlx_jaccl_config_prefers_ring(config.handle())
		if !value {
			if err := lastCErrorIfAny("mlx_jaccl_config_prefers_ring"); err != nil {
				return false, err
			}
		}
		return value, nil
	}
	r1, _, _ := puregoSyscall15X(_mlx_jaccl_config_prefers_ring_addr, uintptr(config.handle()), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	return r1 != 0, nil
}

// ConfigRank calls mlx_jaccl_config_rank.
func ConfigRank(config Config) (int, error) {
	if err := ensureLoaded(); err != nil {
		return 0, err
	}
	if config.IsNil() {
		runtime.LockOSThread()
		defer runtime.UnlockOSThread()
		value := int(_mlx_jaccl_config_rank(config.handle()))
		if value < 0 {
			return value, lastCError("mlx_jaccl_config_rank")
		}
		return value, nil
	}
	r1, _, _ := puregoSyscall15X(_mlx_jaccl_config_rank_addr, uintptr(config.handle()), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	value := int(int32(r1))
	if value < 0 {
		return value, lastCError("mlx_jaccl_config_rank")
	}
	return value, nil
}

// ConfigSetCoordinator calls mlx_jaccl_config_set_coordinator.
func ConfigSetCoordinator(config Config, coordinator string) error {
	if err := ensureLoaded(); err != nil {
		return err
	}
	var coordinatorStack [cStringStackMax]byte
	coordinatorPtr, coordinatorBytes := cStringPtr(coordinator, &coordinatorStack)
	r1, _, _ := puregoSyscall15X(_mlx_jaccl_config_set_coordinator_addr, uintptr(config.handle()), uintptr(unsafe.Pointer(coordinatorPtr)), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	runtime.KeepAlive(coordinatorBytes)
	status := int32(r1)
	if status != 0 {
		return lastCError("mlx_jaccl_config_set_coordinator")
	}
	return nil
}

// ConfigSetDevicesFile calls mlx_jaccl_config_set_devices_file.
func ConfigSetDevicesFile(config Config, path string) error {
	if err := ensureLoaded(); err != nil {
		return err
	}
	var pathStack [cStringStackMax]byte
	pathPtr, pathBytes := cStringPtr(path, &pathStack)
	r1, _, _ := puregoSyscall15X(_mlx_jaccl_config_set_devices_file_addr, uintptr(config.handle()), uintptr(unsafe.Pointer(pathPtr)), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	runtime.KeepAlive(pathBytes)
	status := int32(r1)
	if status != 0 {
		return lastCError("mlx_jaccl_config_set_devices_file")
	}
	return nil
}

// ConfigSetDevicesJSON calls mlx_jaccl_config_set_devices_json.
func ConfigSetDevicesJSON(config Config, data string) error {
	if err := ensureLoaded(); err != nil {
		return err
	}
	var dataStack [cStringStackMax]byte
	dataPtr, dataBytes := cStringPtr(data, &dataStack)
	r1, _, _ := puregoSyscall15X(_mlx_jaccl_config_set_devices_json_addr, uintptr(config.handle()), uintptr(unsafe.Pointer(dataPtr)), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	runtime.KeepAlive(dataBytes)
	status := int32(r1)
	if status != 0 {
		return lastCError("mlx_jaccl_config_set_devices_json")
	}
	return nil
}

// ConfigSetRank calls mlx_jaccl_config_set_rank.
func ConfigSetRank(config Config, rank int) error {
	if err := ensureLoaded(); err != nil {
		return err
	}
	if config.IsNil() {
		runtime.LockOSThread()
		defer runtime.UnlockOSThread()
		status := _mlx_jaccl_config_set_rank(config.handle(), int32(rank))
		return statusError("mlx_jaccl_config_set_rank", status)
	}
	r1, _, _ := puregoSyscall15X(_mlx_jaccl_config_set_rank_addr, uintptr(config.handle()), uintptr(int32(rank)), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	status := int32(r1)
	if status != 0 {
		return lastCError("mlx_jaccl_config_set_rank")
	}
	return nil
}

// ConfigSize calls mlx_jaccl_config_size.
func ConfigSize(config Config) (int, error) {
	if err := ensureLoaded(); err != nil {
		return 0, err
	}
	if config.IsNil() {
		runtime.LockOSThread()
		defer runtime.UnlockOSThread()
		value := int(_mlx_jaccl_config_size(config.handle()))
		if value < 0 {
			return value, lastCError("mlx_jaccl_config_size")
		}
		return value, nil
	}
	r1, _, _ := puregoSyscall15X(_mlx_jaccl_config_size_addr, uintptr(config.handle()), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	value := int(int32(r1))
	if value < 0 {
		return value, lastCError("mlx_jaccl_config_size")
	}
	return value, nil
}

// DTypeSize calls mlx_jaccl_dtype_size.
func DTypeSize(dtype DType) (uint, error) {
	if err := ensureLoaded(); err != nil {
		return 0, err
	}
	if dtype < DTypeBool || dtype > DTypeComplex64 {
		runtime.LockOSThread()
		defer runtime.UnlockOSThread()
		value := _mlx_jaccl_dtype_size(dtype)
		if value == 0 {
			if err := lastCErrorIfAny("mlx_jaccl_dtype_size"); err != nil {
				return 0, err
			}
		}
		return value, nil
	}
	r1, _, _ := puregoSyscall15X(_mlx_jaccl_dtype_size_addr, uintptr(dtype), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	value := uint(r1)
	if value == 0 {
		if err := lastCErrorIfAny("mlx_jaccl_dtype_size"); err != nil {
			return 0, err
		}
	}
	return value, nil
}

// GroupFree calls mlx_jaccl_group_free.
func GroupFree(group Group) error {
	if err := ensureLoaded(); err != nil {
		return err
	}
	if group.IsNil() {
		r1, _, _ := puregoSyscall15X(_mlx_jaccl_group_free_addr, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
		status := int32(r1)
		if status != 0 {
			return lastCError("mlx_jaccl_group_free")
		}
		return nil
	}
	r1, _, _ := puregoSyscall15X(_mlx_jaccl_group_free_addr, uintptr(group.handle()), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	status := int32(r1)
	if status != 0 {
		return lastCError("mlx_jaccl_group_free")
	}
	return nil
}

// GroupNew calls mlx_jaccl_group_new.
func GroupNew() (Group, error) {
	if err := ensureLoaded(); err != nil {
		return Group{}, err
	}
	ptr, _, _ := puregoSyscall15XPtr(_mlx_jaccl_group_new_addr, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	return groupFromHandle(ptr), nil
}

// GroupRank calls mlx_jaccl_group_rank.
func GroupRank(group Group) (int, error) {
	if err := ensureLoaded(); err != nil {
		return 0, err
	}
	if group.IsNil() {
		runtime.LockOSThread()
		defer runtime.UnlockOSThread()
		value := int(_mlx_jaccl_group_rank(group.handle()))
		if value < 0 {
			return value, lastCError("mlx_jaccl_group_rank")
		}
		return value, nil
	}
	r1, _, _ := puregoSyscall15X(_mlx_jaccl_group_rank_addr, uintptr(group.handle()), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	value := int(int32(r1))
	if value < 0 {
		return value, lastCError("mlx_jaccl_group_rank")
	}
	return value, nil
}

// GroupSize calls mlx_jaccl_group_size.
func GroupSize(group Group) (int, error) {
	if err := ensureLoaded(); err != nil {
		return 0, err
	}
	if group.IsNil() {
		runtime.LockOSThread()
		defer runtime.UnlockOSThread()
		value := int(_mlx_jaccl_group_size(group.handle()))
		if value < 0 {
			return value, lastCError("mlx_jaccl_group_size")
		}
		return value, nil
	}
	r1, _, _ := puregoSyscall15X(_mlx_jaccl_group_size_addr, uintptr(group.handle()), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	value := int(int32(r1))
	if value < 0 {
		return value, lastCError("mlx_jaccl_group_size")
	}
	return value, nil
}

// Init calls mlx_jaccl_init.
func Init(strict bool) (Group, error) {
	if err := ensureLoaded(); err != nil {
		return Group{}, err
	}
	var res Group
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	status := _mlx_jaccl_init(&res, strict)
	if err := statusError("mlx_jaccl_init", status); err != nil {
		return Group{}, err
	}
	return res, nil
}

// InitConfig calls mlx_jaccl_init_config.
func InitConfig(config Config, strict bool) (Group, error) {
	if err := ensureLoaded(); err != nil {
		return Group{}, err
	}
	var res Group
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	status := _mlx_jaccl_init_config(&res, config.handle(), strict)
	if err := statusError("mlx_jaccl_init_config", status); err != nil {
		return Group{}, err
	}
	return res, nil
}

// IsAvailable calls mlx_jaccl_is_available.
func IsAvailable() (bool, error) {
	if err := ensureLoaded(); err != nil {
		return false, err
	}
	r1, _, _ := puregoSyscall15X(_mlx_jaccl_is_available_addr, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	return r1 != 0, nil
}

// LastError calls mlx_jaccl_last_error.
func LastError() (string, error) {
	if err := ensureLoaded(); err != nil {
		return "", err
	}
	ptr, _, _ := puregoSyscall15XPtr(_mlx_jaccl_last_error_addr, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
	if ptr == nil {
		if err := lastCErrorIfAny("mlx_jaccl_last_error"); err != nil {
			return "", err
		}
		return "", nil
	}
	return goString((*byte)(ptr)), nil
}

// Recv calls mlx_jaccl_recv.
func Recv(group Group, output unsafe.Pointer, nBytes uint, src int) error {
	if err := ensureLoaded(); err != nil {
		return err
	}
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	status := _mlx_jaccl_recv(group.handle(), output, nBytes, int32(src))
	return statusError("mlx_jaccl_recv", status)
}

// Send calls mlx_jaccl_send.
func Send(group Group, input unsafe.Pointer, nBytes uint, dst int) error {
	if err := ensureLoaded(); err != nil {
		return err
	}
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	status := _mlx_jaccl_send(group.handle(), input, nBytes, int32(dst))
	return statusError("mlx_jaccl_send", status)
}

// NewConfig creates a JACCL configuration.
func NewConfig() (Config, error) {
	return ConfigNewOut()
}

// NewConfigFromEnv creates a JACCL configuration from environment variables.
func NewConfigFromEnv() (Config, error) {
	return ConfigFromEnv()
}

// NewGroup creates an empty JACCL group.
func NewGroup() (Group, error) {
	return GroupNew()
}

// NewGroupFromEnv initializes a JACCL group from environment variables.
func NewGroupFromEnv(strict bool) (Group, error) {
	return Init(strict)
}

// NewGroupWithConfig initializes a JACCL group from config.
func NewGroupWithConfig(config Config, strict bool) (Group, error) {
	return InitConfig(config, strict)
}

// Size reports dtype's element size in bytes.
func (dtype DType) Size() (uint, error) {
	return DTypeSize(dtype)
}

// Close releases config.
func (config Config) Close() error {
	return ConfigFree(config)
}

// SetRank sets config's rank.
func (config Config) SetRank(rank int) error {
	return ConfigSetRank(config, rank)
}

// Rank returns config's rank.
func (config Config) Rank() (int, error) {
	return ConfigRank(config)
}

// SetCoordinator sets config's coordinator address.
func (config Config) SetCoordinator(coordinator string) error {
	return ConfigSetCoordinator(config, coordinator)
}

// Coordinator returns config's coordinator address.
func (config Config) Coordinator() (string, error) {
	return ConfigCoordinator(config)
}

// PreferRing sets whether config prefers ring topology.
func (config Config) PreferRing(prefer bool) error {
	return ConfigPreferRing(config, prefer)
}

// PrefersRing reports whether config prefers ring topology.
func (config Config) PrefersRing() (bool, error) {
	return ConfigPrefersRing(config)
}

// Size returns config's size.
func (config Config) Size() (int, error) {
	return ConfigSize(config)
}

// IsValidMesh reports whether config describes a valid mesh.
func (config Config) IsValidMesh() (bool, error) {
	return ConfigIsValidMesh(config)
}

// IsValidRing reports whether config describes a valid ring.
func (config Config) IsValidRing() (bool, error) {
	return ConfigIsValidRing(config)
}

// SetDevicesFile sets devices from a JSON file.
func (config Config) SetDevicesFile(path string) error {
	return ConfigSetDevicesFile(config, path)
}

// SetDevicesJSON sets devices from a JSON string.
func (config Config) SetDevicesJSON(data string) error {
	return ConfigSetDevicesJSON(config, data)
}

// Close releases group.
func (group Group) Close() error {
	return GroupFree(group)
}

// Rank returns group's rank.
func (group Group) Rank() (int, error) {
	return GroupRank(group)
}

// Size returns group's size.
func (group Group) Size() (int, error) {
	return GroupSize(group)
}

// Barrier waits until every rank enters the barrier.
func (group Group) Barrier() error {
	return Barrier(group)
}

// AllSum computes the element-wise sum across all ranks.
func (group Group) AllSum(input unsafe.Pointer, output unsafe.Pointer, nBytes uint, dtype DType) error {
	return AllSum(group, input, output, nBytes, dtype)
}

// AllMax computes the element-wise maximum across all ranks.
func (group Group) AllMax(input unsafe.Pointer, output unsafe.Pointer, nBytes uint, dtype DType) error {
	return AllMax(group, input, output, nBytes, dtype)
}

// AllMin computes the element-wise minimum across all ranks.
func (group Group) AllMin(input unsafe.Pointer, output unsafe.Pointer, nBytes uint, dtype DType) error {
	return AllMin(group, input, output, nBytes, dtype)
}

// AllGather gathers each rank's input into output in rank order.
func (group Group) AllGather(input unsafe.Pointer, output unsafe.Pointer, nBytes uint) error {
	return AllGather(group, input, output, nBytes)
}

// Send sends bytes to dst.
func (group Group) Send(input unsafe.Pointer, nBytes uint, dst int) error {
	return Send(group, input, nBytes, dst)
}

// Recv receives bytes from src.
func (group Group) Recv(output unsafe.Pointer, nBytes uint, src int) error {
	return Recv(group, output, nBytes, src)
}

// AllSumBytes computes the byte-backed element-wise sum across all ranks.
func (group Group) AllSumBytes(input, output []byte, dtype DType) error {
	if len(output) != len(input) {
		return fmt.Errorf("all sum: output length %d, want %d", len(output), len(input))
	}
	return group.AllSum(bytesPointer(input), bytesPointer(output), uint(len(input)), dtype)
}

// AllMaxBytes computes the byte-backed element-wise maximum across all ranks.
func (group Group) AllMaxBytes(input, output []byte, dtype DType) error {
	if len(output) != len(input) {
		return fmt.Errorf("all max: output length %d, want %d", len(output), len(input))
	}
	return group.AllMax(bytesPointer(input), bytesPointer(output), uint(len(input)), dtype)
}

// AllMinBytes computes the byte-backed element-wise minimum across all ranks.
func (group Group) AllMinBytes(input, output []byte, dtype DType) error {
	if len(output) != len(input) {
		return fmt.Errorf("all min: output length %d, want %d", len(output), len(input))
	}
	return group.AllMin(bytesPointer(input), bytesPointer(output), uint(len(input)), dtype)
}

// AllGatherBytes gathers byte slices from every rank into output in rank order.
func (group Group) AllGatherBytes(input, output []byte) error {
	size, err := group.Size()
	if err != nil {
		return err
	}
	want, err := allGatherBytesLen(size, len(input))
	if err != nil {
		return err
	}
	if len(output) != want {
		return fmt.Errorf("all gather: output length %d, want %d", len(output), want)
	}
	return group.AllGather(bytesPointer(input), bytesPointer(output), uint(len(input)))
}

// SendBytes sends bytes to dst.
func (group Group) SendBytes(input []byte, dst int) error {
	return group.Send(bytesPointer(input), uint(len(input)), dst)
}

// RecvBytes receives bytes from src.
func (group Group) RecvBytes(output []byte, src int) error {
	return group.Recv(bytesPointer(output), uint(len(output)), src)
}
