// Code generated by mlx-c-gen-purego-jaccl from codegen/mlxc-capi.lock.json; DO NOT EDIT.

package jacclc

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sync"
	"sync/atomic"

	"github.com/ebitengine/purego"
)

const (
	envLibraryPath    = "MLX_C_JACCLC_LIB_PATH"
	envLibraryPathAlt = "MLX_JACCLC_LIB_PATH"
)

var (
	loadMu            sync.Mutex
	jacclcLib         uintptr
	jacclcLoaded      atomic.Uintptr
	loadedLibraryPath string
)

// LibraryPath returns the loaded libjacclc path.
func LibraryPath() string {
	loadMu.Lock()
	defer loadMu.Unlock()
	return loadedLibraryPath
}

// Load loads libjacclc from the environment or standard library locations.
func Load() error {
	return loadPath("")
}

// LoadPath loads libjacclc from path. If path is a directory, it is expected
// to contain libjacclc and its sibling dependencies.
func LoadPath(path string) error {
	return loadPath(path)
}

func ensureLoaded() error {
	if jacclcLoaded.Load() != 0 {
		return nil
	}
	return Load()
}

func loadPath(path string) error {
	loadMu.Lock()
	defer loadMu.Unlock()
	if jacclcLib != 0 {
		if path == "" || sameLibraryPath(path, loadedLibraryPath) {
			return nil
		}
		return fmt.Errorf("jacclc already loaded from %s", loadedLibraryPath)
	}
	if path == "" {
		resolved, err := resolveLibraryPath()
		if err != nil {
			return err
		}
		path = resolved
	} else {
		path = resolveLibraryOverride(path)
	}
	if err := preloadSiblingLibraries(path); err != nil {
		return err
	}
	lib, err := purego.Dlopen(path, purego.RTLD_NOW|purego.RTLD_GLOBAL)
	if err != nil {
		return fmt.Errorf("load %s: %w", path, err)
	}
	if err := registerJACCLFunctions(lib); err != nil {
		return err
	}
	jacclcLib = lib
	loadedLibraryPath = path
	jacclcLoaded.Store(lib)
	return nil
}

func sameLibraryPath(path, loaded string) bool {
	path = resolveLibraryOverride(path)
	if path == loaded {
		return true
	}
	absPath, err1 := filepath.Abs(path)
	absLoaded, err2 := filepath.Abs(loaded)
	return err1 == nil && err2 == nil && absPath == absLoaded
}

func resolveLibraryPath() (string, error) {
	for _, name := range []string{envLibraryPath, envLibraryPathAlt} {
		if value := os.Getenv(name); value != "" {
			return resolveLibraryOverride(value), nil
		}
	}

	libName := libraryFileName("libjacclc")
	for _, dir := range sourceSearchDirs() {
		candidate := filepath.Join(dir, libName)
		if _, err := os.Stat(candidate); err == nil {
			return candidate, nil
		}
	}

	paths := []string{
		filepath.Join(os.Getenv("HOME"), "lib", libName),
		filepath.Join(os.Getenv("HOME"), ".local", "lib", libName),
		"/usr/local/lib/" + libName,
	}
	if runtime.GOOS == "darwin" {
		paths = append(paths, "/opt/homebrew/lib/"+libName)
	}
	for _, path := range paths {
		if _, err := os.Stat(path); err == nil {
			return path, nil
		}
	}
	return "", fmt.Errorf("libjacclc not found; set %s to a libjacclc file or directory", envLibraryPath)
}

func sourceSearchDirs() []string {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return nil
	}
	dir := filepath.Dir(file)
	for depth := 0; depth < 10; depth++ {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return []string{
				filepath.Join(dir, "build-shared"),
				filepath.Join(dir, "build-Release"),
				filepath.Join(dir, "build-Debug"),
				filepath.Join(dir, "build"),
				filepath.Join(dir, "install", "lib"),
			}
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return nil
		}
		dir = parent
	}
	return nil
}

func resolveLibraryOverride(path string) string {
	info, err := os.Stat(path)
	if err != nil || !info.IsDir() {
		return path
	}
	return filepath.Join(path, libraryFileName("libjacclc"))
}

func libraryFileName(base string) string {
	switch runtime.GOOS {
	case "darwin":
		return base + ".dylib"
	case "linux":
		return base + ".so"
	default:
		return base
	}
}

func preloadSiblingLibraries(path string) error {
	dir := filepath.Dir(path)
	for _, base := range []string{"libjaccl", "libmlx"} {
		candidate := filepath.Join(dir, libraryFileName(base))
		if _, err := os.Stat(candidate); err != nil {
			continue
		}
		if _, err := purego.Dlopen(candidate, purego.RTLD_NOW|purego.RTLD_GLOBAL); err != nil {
			return fmt.Errorf("preload %s: %w", candidate, err)
		}
	}
	return nil
}

func registerLibFunc(fptr any, lib uintptr, name string) (err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("register %s: %v", name, r)
		}
	}()
	purego.RegisterLibFunc(fptr, lib, name)
	return nil
}
