// Code generated by mlx-c-gen-purego-jaccl from codegen/mlxc-capi.lock.json; DO NOT EDIT.

package jacclc

import "unsafe"

// Config wraps mlx_jaccl_config.
type Config struct {
	ctx unsafe.Pointer
}

// Ptr returns the underlying pointer.
func (t Config) Ptr() unsafe.Pointer {
	return t.ctx
}

// IsNil reports whether the underlying pointer is nil.
func (t Config) IsNil() bool {
	return t.ctx == nil
}

func (t Config) handle() unsafe.Pointer {
	return t.ctx
}

func configFromHandle(handle unsafe.Pointer) Config {
	return Config{ctx: handle}
}

// Group wraps mlx_jaccl_group.
type Group struct {
	ctx unsafe.Pointer
}

// Ptr returns the underlying pointer.
func (t Group) Ptr() unsafe.Pointer {
	return t.ctx
}

// IsNil reports whether the underlying pointer is nil.
func (t Group) IsNil() bool {
	return t.ctx == nil
}

func (t Group) handle() unsafe.Pointer {
	return t.ctx
}

func groupFromHandle(handle unsafe.Pointer) Group {
	return Group{ctx: handle}
}

// DType is a JACCL element type.
type DType int32

const (
	DTypeBool      DType = 0
	DTypeInt8      DType = 1
	DTypeInt16     DType = 2
	DTypeInt32     DType = 3
	DTypeInt64     DType = 4
	DTypeUint8     DType = 5
	DTypeUint16    DType = 6
	DTypeUint32    DType = 7
	DTypeUint64    DType = 8
	DTypeFloat16   DType = 9
	DTypeBFloat16  DType = 10
	DTypeFloat32   DType = 11
	DTypeFloat64   DType = 12
	DTypeComplex64 DType = 13
)
